### ISSUE TITLE
Feature: allow shallow symlinks

### ISSUE THREAD

**Issue by utkarshgupta137** [RaphGL/Tuckr#21] opened 2023-04-04 20:12 UTC
GNU stow can do shallow symlinking i.e. if the directory is already present, it will symlink the files inside it, leaving the directory untouched. This allows other files to be in the same directory as config files.
[prezto](https://github.com/sorin-ionescu/prezto/#manual) for example supports using ZDOTDIR, but it needs the .zprezto folder to be in the same folder as my rc files.
Also, [lazygit](https://github.com/jesseduffield/lazygit) creates a state.yml file which I don't want in my dotfiles repo.

**Comment by RaphGL** [comment] 2023-04-06 23:45
I decided to tackle this today and honestly it's turned out to be harder to implement then I thought. Mostly because of the assumptions I initially had on how validation should work and the data structures I chose. I've been tweaking a bit and managed to implement shallow symlinks but it completely broke the validation.

So I'm going to try and move from using HashSets to HashMaps in an attempt to make recognizing that a parent has been symlinked. The issue is that the original implementation simplified things by making so one group was one symlink, but with shallow symlinks a group can be a bunch of symlinks and it might not even own the group folder. So I need a way to be able to check every file, but most files won't be actual symlinks so I need to detect that it's parent has been symlinked.

If I manage to fix symlink validation I'll push the changes to main, if it proves to be too annoying to implement I might end up postponing it for when I find a solution

**Comment by RaphGL** [comment] 2023-06-03 18:32
Marked this as "help wanted" as I've been struggling to implement this correctly for the past 2 months.
I'm not sure how to approach this problem yet, I've thought about implementing some sort of BFS or something to be able to detect files that share at least one parent but I haven't gotten around to try that yet.

**Closed** 2024-07-06 23:33 UTC
Labels: enhancement, help wanted

**Comment by RaphGL** [comment] 2024-07-06 23:37
This issue is now fixed. As far as I'm aware, shallow symlinking is working properly. Bare in mind that this is likely a breaking change. So I recommend doing the following:

- Before upgrade remove all your dotfiles
```sh
$ tuckr rm \*
```
- Once you're done you can resymlink and it will use the new shallow symlinking strategy
```sh
$ tuckr add \*
```

Note: adding shallow symlinks required changing things a little bit so conflict detection isn't working properly for now cause of the difference in how symlinks are being done now (will be fixing it very soon). you'll just see your groups on "not symlinked" for even if they're in conflict, forcing or adopting groups still works as intended.
